### PR TITLE
abstracted decode and encode url for other purposes

### PR DESCRIPTION
**Pull request by mattbeard03**
created abstraction of self made URL decode and encode algorithm, to use with other filtering items.

### CODE REVIEW

**Comment by sirclek** [comment]
Do u want to merge this now or should we wait for more filtering stuff that will use this?

**Comment by mattbeard03** [comment]
> Do u want to merge this now or should we wait for more filtering stuff that will use this?

Merge now is fine, its a useful abstraction for other people if they are routing filters

**Comment by ngu892** [comment]
I haved run this request on codespace and it is working well 
thank you:)

**Review by ngu892 — APPROVED** [review]
Checking approvement

**Review by ngu892 — APPROVED** [review]
Approvement

**Pull request merged**
